name: Terraform Azure Deployment - Key Vault

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

   
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Set up Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Terraform variables
      env:
        TF_VAR_service_principal_object_id: ${{ secrets.SERVICE_PRINCIPLE_OBJECT_ID }}
        TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}  # Use a secret or env variable
      run: |
        echo "Service Principal Object ID and TENANT ID set as a variable"
  
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform-Keyvault

  
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Terraform-Keyvault

    #- name: Output Service Principal Object ID
    #  run: |
    #       echo "The Object ID of the Service Principal is: ${{ secrets.SERVICE_PRINCIPLE_OBJECT_ID }}"

    - name: Terraform Plan
      run: terraform plan -var="service_principal_object_id=${{ secrets.SERVICE_PRINCIPLE_OBJECT_ID }}",
       -var="tenant_id=${{ secrets.TENANT_ID }}" -out=tfplan
      working-directory: ./Terraform-Keyvault

   
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./Terraform-Keyvault

    